import { University } from '@/types/university';

/**
 * In-memory database with real university data
 * In production, this would be replaced with a proper database (PostgreSQL, MongoDB, etc.)
 */
export const universities: University[] = [
  // USA Universities
  {
    id: 'mit-usa',
    name: 'Massachusetts Institute of Technology',
    country: 'United States',
    city: 'Cambridge',
    state: 'Massachusetts',
    tuitionFee: 57986,
    currency: 'USD',
    ranking: 1,
    establishedYear: 1861,
    imageUrl: '/universities/mit.jpg',
    studentPopulation: 11934,
    internationalStudents: 33,
    acceptanceRate: 3.9,
    graduationRate: 96,
    programs: ['Computer Science', 'Engineering', 'Physics', 'Economics', 'Mathematics', 'Biology'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 45000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 95,
    avgStartingSalary: 95000,
    website: 'https://www.mit.edu',
    description: 'World-renowned research university with cutting-edge technology and innovation programs.',
  },
  {
    id: 'stanford-usa',
    name: 'Stanford University',
    country: 'United States',
    city: 'Stanford',
    state: 'California',
    tuitionFee: 58416,
    currency: 'USD',
    ranking: 2,
    establishedYear: 1885,
    imageUrl: '/universities/stanford.jpg',
    studentPopulation: 17249,
    internationalStudents: 23,
    acceptanceRate: 4.3,
    graduationRate: 94,
    programs: ['Computer Science', 'Business', 'Engineering', 'Medicine', 'Law', 'Education'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 50000,
    campusType: 'Suburban',
    housingAvailable: true,
    employmentRate: 93,
    avgStartingSalary: 92000,
    website: 'https://www.stanford.edu',
    description: 'Leading research university in Silicon Valley, known for entrepreneurship and innovation.',
  },
  {
    id: 'harvard-usa',
    name: 'Harvard University',
    country: 'United States',
    city: 'Cambridge',
    state: 'Massachusetts',
    tuitionFee: 54269,
    currency: 'USD',
    ranking: 3,
    establishedYear: 1636,
    imageUrl: '/universities/harvard.jpg',
    studentPopulation: 23731,
    internationalStudents: 25,
    acceptanceRate: 4.6,
    graduationRate: 97,
    programs: ['Law', 'Business', 'Medicine', 'Government', 'Economics', 'Computer Science'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 48000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 94,
    avgStartingSalary: 89000,
    website: 'https://www.harvard.edu',
    description: 'Oldest institution of higher education in the United States with unparalleled academic excellence.',
  },
  {
    id: 'caltech-usa',
    name: 'California Institute of Technology',
    country: 'United States',
    city: 'Pasadena',
    state: 'California',
    tuitionFee: 58479,
    currency: 'USD',
    ranking: 4,
    establishedYear: 1891,
    imageUrl: '/universities/caltech.jpg',
    studentPopulation: 2397,
    internationalStudents: 31,
    acceptanceRate: 6.4,
    graduationRate: 92,
    programs: ['Physics', 'Engineering', 'Chemistry', 'Astronomy', 'Mathematics', 'Computer Science'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 42000,
    campusType: 'Suburban',
    housingAvailable: true,
    employmentRate: 91,
    avgStartingSalary: 88000,
    website: 'https://www.caltech.edu',
    description: 'Elite science and engineering institution with exceptional faculty-to-student ratio.',
  },
  {
    id: 'princeton-usa',
    name: 'Princeton University',
    country: 'United States',
    city: 'Princeton',
    state: 'New Jersey',
    tuitionFee: 57410,
    currency: 'USD',
    ranking: 6,
    establishedYear: 1746,
    imageUrl: '/universities/princeton.jpg',
    studentPopulation: 8842,
    internationalStudents: 12,
    acceptanceRate: 5.8,
    graduationRate: 96,
    programs: ['Economics', 'Public Policy', 'Engineering', 'Mathematics', 'Physics', 'Computer Science'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 55000,
    campusType: 'Suburban',
    housingAvailable: true,
    employmentRate: 92,
    avgStartingSalary: 85000,
    website: 'https://www.princeton.edu',
    description: 'Ivy League university known for undergraduate teaching and research excellence.',
  },

  // UK Universities
  {
    id: 'oxford-uk',
    name: 'University of Oxford',
    country: 'United Kingdom',
    city: 'Oxford',
    state: 'Oxfordshire',
    tuitionFee: 26770,
    currency: 'GBP',
    ranking: 5,
    establishedYear: 1096,
    imageUrl: '/universities/oxford.jpg',
    studentPopulation: 24515,
    internationalStudents: 43,
    acceptanceRate: 17.5,
    graduationRate: 95,
    programs: ['Law', 'Philosophy', 'Medicine', 'English', 'History', 'Computer Science'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 15000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 93,
    avgStartingSalary: 65000,
    website: 'https://www.ox.ac.uk',
    description: 'World\'s oldest English-speaking university with collegiate system and tutorial learning.',
  },
  {
    id: 'cambridge-uk',
    name: 'University of Cambridge',
    country: 'United Kingdom',
    city: 'Cambridge',
    state: 'Cambridgeshire',
    tuitionFee: 25734,
    currency: 'GBP',
    ranking: 7,
    establishedYear: 1209,
    imageUrl: '/universities/cambridge.jpg',
    studentPopulation: 24450,
    internationalStudents: 39,
    acceptanceRate: 21,
    graduationRate: 94,
    programs: ['Mathematics', 'Natural Sciences', 'Engineering', 'Medicine', 'Law', 'Economics'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 14000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 91,
    avgStartingSalary: 63000,
    website: 'https://www.cam.ac.uk',
    description: 'Ancient university known for groundbreaking research and academic excellence.',
  },
  {
    id: 'imperial-uk',
    name: 'Imperial College London',
    country: 'United Kingdom',
    city: 'London',
    state: 'Greater London',
    tuitionFee: 34500,
    currency: 'GBP',
    ranking: 8,
    establishedYear: 1907,
    imageUrl: '/universities/imperial.jpg',
    studentPopulation: 20000,
    internationalStudents: 60,
    acceptanceRate: 14.3,
    graduationRate: 92,
    programs: ['Engineering', 'Medicine', 'Natural Sciences', 'Business', 'Computer Science'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 12000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 90,
    avgStartingSalary: 68000,
    website: 'https://www.imperial.ac.uk',
    description: 'Science, engineering, medicine and business focused institution in the heart of London.',
  },
  {
    id: 'ucl-uk',
    name: 'University College London',
    country: 'United Kingdom',
    city: 'London',
    state: 'Greater London',
    tuitionFee: 28500,
    currency: 'GBP',
    ranking: 9,
    establishedYear: 1826,
    imageUrl: '/universities/ucl.jpg',
    studentPopulation: 43800,
    internationalStudents: 53,
    acceptanceRate: 11,
    graduationRate: 89,
    programs: ['Architecture', 'Law', 'Engineering', 'Medicine', 'Economics', 'Computer Science'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 10000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 88,
    avgStartingSalary: 61000,
    website: 'https://www.ucl.ac.uk',
    description: 'London\'s global university with diverse community and interdisciplinary research.',
  },
  {
    id: 'edinburgh-uk',
    name: 'University of Edinburgh',
    country: 'United Kingdom',
    city: 'Edinburgh',
    state: 'Scotland',
    tuitionFee: 23100,
    currency: 'GBP',
    ranking: 15,
    establishedYear: 1583,
    imageUrl: '/universities/edinburgh.jpg',
    studentPopulation: 35000,
    internationalStudents: 45,
    acceptanceRate: 40,
    graduationRate: 87,
    programs: ['Medicine', 'Law', 'Engineering', 'Business', 'Informatics', 'Arts'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 8000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 85,
    avgStartingSalary: 55000,
    website: 'https://www.ed.ac.uk',
    description: 'Historic Scottish university with strong research and beautiful city location.',
  },

  // Canada Universities
  {
    id: 'toronto-canada',
    name: 'University of Toronto',
    country: 'Canada',
    city: 'Toronto',
    state: 'Ontario',
    tuitionFee: 45690,
    currency: 'CAD',
    ranking: 21,
    establishedYear: 1827,
    imageUrl: '/universities/toronto.jpg',
    studentPopulation: 95055,
    internationalStudents: 24,
    acceptanceRate: 43,
    graduationRate: 86,
    programs: ['Computer Science', 'Engineering', 'Business', 'Medicine', 'Law', 'Arts & Sciences'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 15000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 84,
    avgStartingSalary: 52000,
    website: 'https://www.utoronto.ca',
    description: 'Canada\'s top university with three campuses and world-class research facilities.',
  },
  {
    id: 'mcgill-canada',
    name: 'McGill University',
    country: 'Canada',
    city: 'Montreal',
    state: 'Quebec',
    tuitionFee: 24000,
    currency: 'CAD',
    ranking: 30,
    establishedYear: 1821,
    imageUrl: '/universities/mcgill.jpg',
    studentPopulation: 40000,
    internationalStudents: 31,
    acceptanceRate: 46,
    graduationRate: 83,
    programs: ['Medicine', 'Law', 'Engineering', 'Management', 'Arts', 'Science'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 12000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 82,
    avgStartingSalary: 48000,
    website: 'https://www.mcgill.ca',
    description: 'Internationally recognized university in the heart of Montreal.',
  },
  {
    id: 'ubc-canada',
    name: 'University of British Columbia',
    country: 'Canada',
    city: 'Vancouver',
    state: 'British Columbia',
    tuitionFee: 39289,
    currency: 'CAD',
    ranking: 34,
    establishedYear: 1908,
    imageUrl: '/universities/ubc.jpg',
    studentPopulation: 66000,
    internationalStudents: 28,
    acceptanceRate: 52,
    graduationRate: 81,
    programs: ['Engineering', 'Business', 'Computer Science', 'Forestry', 'Medicine', 'Arts'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 10000,
    campusType: 'Suburban',
    housingAvailable: true,
    employmentRate: 80,
    avgStartingSalary: 47000,
    website: 'https://www.ubc.ca',
    description: 'Beautiful campus with ocean and mountain views, strong research programs.',
  },

  // Australia Universities
  {
    id: 'melbourne-australia',
    name: 'University of Melbourne',
    country: 'Australia',
    city: 'Melbourne',
    state: 'Victoria',
    tuitionFee: 44000,
    currency: 'AUD',
    ranking: 14,
    establishedYear: 1853,
    imageUrl: '/universities/melbourne.jpg',
    studentPopulation: 51000,
    internationalStudents: 42,
    acceptanceRate: 70,
    graduationRate: 85,
    programs: ['Medicine', 'Law', 'Business', 'Engineering', 'Arts', 'Science'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 20000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 83,
    avgStartingSalary: 65000,
    website: 'https://www.unimelb.edu.au',
    description: 'Australia\'s leading university with strong international reputation.',
  },
  {
    id: 'anu-australia',
    name: 'Australian National University',
    country: 'Australia',
    city: 'Canberra',
    state: 'Australian Capital Territory',
    tuitionFee: 42000,
    currency: 'AUD',
    ranking: 27,
    establishedYear: 1946,
    imageUrl: '/universities/anu.jpg',
    studentPopulation: 25500,
    internationalStudents: 44,
    acceptanceRate: 35,
    graduationRate: 84,
    programs: ['Public Policy', 'International Relations', 'Science', 'Engineering', 'Law', 'Economics'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 18000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 82,
    avgStartingSalary: 62000,
    website: 'https://www.anu.edu.au',
    description: 'National research university with strong focus on policy and international studies.',
  },
  {
    id: 'sydney-australia',
    name: 'University of Sydney',
    country: 'Australia',
    city: 'Sydney',
    state: 'New South Wales',
    tuitionFee: 43000,
    currency: 'AUD',
    ranking: 19,
    establishedYear: 1850,
    imageUrl: '/universities/sydney.jpg',
    studentPopulation: 74000,
    internationalStudents: 40,
    acceptanceRate: 30,
    graduationRate: 83,
    programs: ['Medicine', 'Law', 'Business', 'Engineering', 'Architecture', 'Arts'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 17000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 81,
    avgStartingSalary: 63000,
    website: 'https://www.sydney.edu.au',
    description: 'Australia\'s first university with beautiful sandstone architecture and strong programs.',
  },

  // Singapore Universities
  {
    id: 'nus-singapore',
    name: 'National University of Singapore',
    country: 'Singapore',
    city: 'Singapore',
    tuitionFee: 27500,
    currency: 'SGD',
    ranking: 11,
    establishedYear: 1905,
    imageUrl: '/universities/nus.jpg',
    studentPopulation: 40000,
    internationalStudents: 30,
    acceptanceRate: 5,
    graduationRate: 90,
    programs: ['Engineering', 'Business', 'Computer Science', 'Law', 'Medicine', 'Design'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 20000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 89,
    avgStartingSalary: 55000,
    website: 'https://www.nus.edu.sg',
    description: 'Asia\'s leading university with strong global partnerships and innovation focus.',
  },
  {
    id: 'ntu-singapore',
    name: 'Nanyang Technological University',
    country: 'Singapore',
    city: 'Singapore',
    tuitionFee: 26000,
    currency: 'SGD',
    ranking: 26,
    establishedYear: 1991,
    imageUrl: '/universities/ntu.jpg',
    studentPopulation: 33500,
    internationalStudents: 25,
    acceptanceRate: 15,
    graduationRate: 88,
    programs: ['Engineering', 'Business', 'Science', 'Education', 'Media', 'Medicine'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 18000,
    campusType: 'Suburban',
    housingAvailable: true,
    employmentRate: 87,
    avgStartingSalary: 52000,
    website: 'https://www.ntu.edu.sg',
    description: 'Young research-intensive university with smart campus and cutting-edge facilities.',
  },

  // Additional Universities for diversity
  {
    id: 'eth-zurich',
    name: 'ETH Zurich',
    country: 'Switzerland',
    city: 'Zurich',
    tuitionFee: 1600,
    currency: 'CHF',
    ranking: 10,
    establishedYear: 1855,
    imageUrl: '/universities/eth.jpg',
    studentPopulation: 24500,
    internationalStudents: 40,
    acceptanceRate: 27,
    graduationRate: 89,
    programs: ['Engineering', 'Computer Science', 'Physics', 'Mathematics', 'Architecture', 'Chemistry'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 5000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 91,
    avgStartingSalary: 95000,
    website: 'https://www.ethz.ch',
    description: 'Leading science and technology university in the heart of Europe.',
  },
  {
    id: 'tokyo-japan',
    name: 'University of Tokyo',
    country: 'Japan',
    city: 'Tokyo',
    tuitionFee: 535800,
    currency: 'JPY',
    ranking: 23,
    establishedYear: 1877,
    imageUrl: '/universities/tokyo.jpg',
    studentPopulation: 28000,
    internationalStudents: 12,
    acceptanceRate: 35,
    graduationRate: 86,
    programs: ['Engineering', 'Science', 'Law', 'Economics', 'Medicine', 'Arts'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 500000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 88,
    avgStartingSalary: 5000000,
    website: 'https://www.u-tokyo.ac.jp',
    description: 'Japan\'s most prestigious university with world-class research.',
  },
  {
    id: 'tsinghua-china',
    name: 'Tsinghua University',
    country: 'China',
    city: 'Beijing',
    tuitionFee: 30000,
    currency: 'CNY',
    ranking: 12,
    establishedYear: 1911,
    imageUrl: '/universities/tsinghua.jpg',
    studentPopulation: 53000,
    internationalStudents: 11,
    acceptanceRate: 2,
    graduationRate: 92,
    programs: ['Engineering', 'Computer Science', 'Economics', 'Architecture', 'Law', 'Medicine'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 20000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 90,
    avgStartingSalary: 150000,
    website: 'https://www.tsinghua.edu.cn',
    description: 'China\'s top university for engineering and technology.',
  },
  {
    id: 'peking-china',
    name: 'Peking University',
    country: 'China',
    city: 'Beijing',
    tuitionFee: 28000,
    currency: 'CNY',
    ranking: 17,
    establishedYear: 1898,
    imageUrl: '/universities/peking.jpg',
    studentPopulation: 47000,
    internationalStudents: 13,
    acceptanceRate: 1,
    graduationRate: 91,
    programs: ['Liberal Arts', 'Science', 'Law', 'Economics', 'Medicine', 'International Relations'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 18000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 89,
    avgStartingSalary: 140000,
    website: 'https://www.pku.edu.cn',
    description: 'Comprehensive research university with strong humanities and sciences.',
  },
  {
    id: 'sorbonne-france',
    name: 'Sorbonne University',
    country: 'France',
    city: 'Paris',
    tuitionFee: 2770,
    currency: 'EUR',
    ranking: 60,
    establishedYear: 1257,
    imageUrl: '/universities/sorbonne.jpg',
    studentPopulation: 55000,
    internationalStudents: 20,
    acceptanceRate: 55,
    graduationRate: 78,
    programs: ['Arts', 'Humanities', 'Science', 'Medicine', 'Engineering', 'Law'],
    researchOutput: 'High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 5000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 76,
    avgStartingSalary: 35000,
    website: 'https://www.sorbonne-universite.fr',
    description: 'Historic university in the Latin Quarter with rich academic tradition.',
  },
  {
    id: 'waterloo-canada',
    name: 'University of Waterloo',
    country: 'Canada',
    city: 'Waterloo',
    state: 'Ontario',
    tuitionFee: 36000,
    currency: 'CAD',
    ranking: 149,
    establishedYear: 1957,
    imageUrl: '/universities/waterloo.jpg',
    studentPopulation: 42000,
    internationalStudents: 22,
    acceptanceRate: 53,
    graduationRate: 80,
    programs: ['Computer Science', 'Engineering', 'Mathematics', 'Business', 'Science', 'Health'],
    researchOutput: 'High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 8000,
    campusType: 'Suburban',
    housingAvailable: true,
    employmentRate: 90,
    avgStartingSalary: 65000,
    website: 'https://uwaterloo.ca',
    description: 'Known for co-op programs and strong ties with tech industry.',
  },
  {
    id: 'michigan-usa',
    name: 'University of Michigan',
    country: 'United States',
    city: 'Ann Arbor',
    state: 'Michigan',
    tuitionFee: 52266,
    currency: 'USD',
    ranking: 25,
    establishedYear: 1817,
    imageUrl: '/universities/michigan.jpg',
    studentPopulation: 48000,
    internationalStudents: 17,
    acceptanceRate: 23,
    graduationRate: 91,
    programs: ['Engineering', 'Business', 'Medicine', 'Law', 'Arts', 'Public Policy'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 25000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 87,
    avgStartingSalary: 72000,
    website: 'https://umich.edu',
    description: 'Public research university with comprehensive programs and strong athletics.',
  },
  {
    id: 'duke-usa',
    name: 'Duke University',
    country: 'United States',
    city: 'Durham',
    state: 'North Carolina',
    tuitionFee: 60435,
    currency: 'USD',
    ranking: 50,
    establishedYear: 1838,
    imageUrl: '/universities/duke.jpg',
    studentPopulation: 17000,
    internationalStudents: 11,
    acceptanceRate: 7.7,
    graduationRate: 95,
    programs: ['Medicine', 'Law', 'Business', 'Engineering', 'Public Policy', 'Arts & Sciences'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 40000,
    campusType: 'Suburban',
    housingAvailable: true,
    employmentRate: 90,
    avgStartingSalary: 78000,
    website: 'https://duke.edu',
    description: 'Private research university with Gothic architecture and strong programs.',
  },
  {
    id: 'warwick-uk',
    name: 'University of Warwick',
    country: 'United Kingdom',
    city: 'Coventry',
    state: 'West Midlands',
    tuitionFee: 24800,
    currency: 'GBP',
    ranking: 67,
    establishedYear: 1965,
    imageUrl: '/universities/warwick.jpg',
    studentPopulation: 28000,
    internationalStudents: 35,
    acceptanceRate: 14,
    graduationRate: 86,
    programs: ['Business', 'Economics', 'Engineering', 'Computer Science', 'Law', 'Mathematics'],
    researchOutput: 'High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 7000,
    campusType: 'Suburban',
    housingAvailable: true,
    employmentRate: 83,
    avgStartingSalary: 58000,
    website: 'https://warwick.ac.uk',
    description: 'Young research university with strong business and economics programs.',
  },
  {
    id: 'queensland-australia',
    name: 'University of Queensland',
    country: 'Australia',
    city: 'Brisbane',
    state: 'Queensland',
    tuitionFee: 41000,
    currency: 'AUD',
    ranking: 43,
    establishedYear: 1909,
    imageUrl: '/universities/queensland.jpg',
    studentPopulation: 53600,
    internationalStudents: 38,
    acceptanceRate: 50,
    graduationRate: 82,
    programs: ['Science', 'Engineering', 'Business', 'Medicine', 'Law', 'Education'],
    researchOutput: 'Very High',
    scholarshipAvailable: true,
    avgScholarshipAmount: 15000,
    campusType: 'Urban',
    housingAvailable: true,
    employmentRate: 80,
    avgStartingSalary: 61000,
    website: 'https://uq.edu.au',
    description: 'Research-intensive university with beautiful campus and subtropical location.',
  },
];

/**
 * Get unique filter options from database
 */
export function getFilterOptions() {
  const countries = [...new Set(universities.map(u => u.country))].sort();
  const cities = [...new Set(universities.map(u => u.city))].sort();
  const programs = [...new Set(universities.flatMap(u => u.programs))].sort();
  
  return { countries, cities, programs };
}
